### ISSUE TITLE
Inconsistent timeout when bootkube fails to startup 

### ISSUE THREAD

**Issue by ipochi** [kinvolk/bootkube#16]
Currently its seems that the code has a timeout set as seen [here](https://github.com/kinvolk/bootkube/blob/kinvolk-master/pkg/bootkube/bootkube.go#L14)

However, this is not followed or there is a bug.

Output from different Lokomotive pipelines confirm this:

[This build is still ongoing at the time of writing](https://yard.lokomotive-k8s.net/builds/43351)
```
module.packet-ci1606199406-al.null_resource.bootkube-start: Still creating... [1h12m0s elapsed]
module.packet-ci1606199406-al.null_resource.bootkube-start: Still creating... [1h12m10s elapsed]
```

[Packet pipeline when the build stopped due to timeout](https://yard.lokomotive-k8s.net/builds/43352)
```
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m10s elapsed]
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m20s elapsed]
module.packet-ci1606199412-bd.null_resource.bootkube-start: Still creating... [51m30s elapsed]
```
[AWS pipeline](https://yard.lokomotive-k8s.net/builds/43350)
```
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [55m40s elapsed]
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [55m50s elapsed]
module.aws-ci1606199395-yy.null_resource.bootkube-start: Still creating... [56m0s elapsed]
```

**Comment by invidian** [comment]
This is likely caused because we do not set the timeout on Helm install action: https://godoc.org/helm.sh/helm/v3/pkg/action#Install.
